using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MpegData.v1
{
    public static class Genre
    {
        public static System.Collections.ObjectModel.ReadOnlyCollection<string> GetGenres()
        {
            List<string> result = new List<string>();

            result.Add("Blues");
            result.Add("Classic Rock");
            result.Add("Country");
            result.Add("Dance");
            result.Add("Disco");
            result.Add("Funk");
            result.Add("Grunge");
            result.Add("Hip-Hop");
            result.Add("Jazz");
            result.Add("Metal");
            result.Add("New Age");
            result.Add("Oldies");
            result.Add("Other");
            result.Add("Pop");
            result.Add("R&B");
            result.Add("Rap");
            result.Add("Reggae");
            result.Add("Rock");
            result.Add("Techno");
            result.Add("Industrial");
            result.Add("Alternative");
            result.Add("Ska");
            result.Add("Death Metal");
            result.Add("Pranks");
            result.Add("Soundtrack");
            result.Add("Euro-Techno");
            result.Add("Ambient");
            result.Add("Trip-Hop");
            result.Add("Vocal");
            result.Add("Jazz+Funk");
            result.Add("Fusion");
            result.Add("Trance");
            result.Add("Classical");
            result.Add("Instrumental");
            result.Add("Acid");
            result.Add("House");
            result.Add("Game");
            result.Add("Sound Clip");
            result.Add("Gospel");
            result.Add("Noise");
            result.Add("AlternRock");
            result.Add("Bass");
            result.Add("Soul");
            result.Add("Punk");
            result.Add("Space");
            result.Add("Meditative");
            result.Add("Instrumental Pop");
            result.Add("Instrumental Rock");
            result.Add("Ethnic");
            result.Add("Gothic");
            result.Add("Darkwave");
            result.Add("Techno-Industrial");
            result.Add("Electronic");
            result.Add("Pop-Folk");
            result.Add("Eurodance");
            result.Add("Dream");
            result.Add("Southern Rock");
            result.Add("Comedy");
            result.Add("Cult");
            result.Add("Gangsta");
            result.Add("Top 40");
            result.Add("Christian Rap");
            result.Add("Pop/Funk");
            result.Add("Jungle");
            result.Add("Native American");
            result.Add("Cabaret");
            result.Add("New Wave");
            result.Add("Psychadelic");
            result.Add("Rave");
            result.Add("Showtunes");
            result.Add("Trailer");
            result.Add("Lo-Fi");
            result.Add("Tribal");
            result.Add("Acid Punk");
            result.Add("Acid Jazz");
            result.Add("Polka");
            result.Add("Retro");
            result.Add("Musical");
            result.Add("Rock & Roll");
            result.Add("Hard Rock");
            result.Add("Folk");
            result.Add("Folk-Rock");
            result.Add("National Folk");
            result.Add("Swing");
            result.Add("Fast Fusion");
            result.Add("Bebob");
            result.Add("Latin");
            result.Add("Revival");
            result.Add("Celtic");
            result.Add("Bluegrass");
            result.Add("Avantgarde");
            result.Add("Gothic Rock");
            result.Add("Progressive Rock");
            result.Add("Psychedelic Rock");
            result.Add("Symphonic Rock");
            result.Add("Slow Rock");
            result.Add("Big Band");
            result.Add("Chorus");
            result.Add("Easy Listening");
            result.Add("Acoustic");
            result.Add("Humour");
            result.Add("Speech");
            result.Add("Chanson");
            result.Add("Opera");
            result.Add("Chamber Music");
            result.Add("Sonata");
            result.Add("Symphony");
            result.Add("Booty Bass");
            result.Add("Primus");
            result.Add("Porn Groove");
            result.Add("Satire");
            result.Add("Slow Jam");
            result.Add("Club");
            result.Add("Tango");
            result.Add("Samba");
            result.Add("Folklore");
            result.Add("Ballad");
            result.Add("Power Ballad");
            result.Add("Rhythmic Soul");
            result.Add("Freestyle");
            result.Add("Duet");
            result.Add("Punk Rock");
            result.Add("Drum Solo");
            result.Add("A capella");
            result.Add("Euro-House");
            result.Add("Dance Hall");

            return result.AsReadOnly();
        }
    }
}
